# Generated by Django 2.1.2 on 2018-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('docfile', models.FileField(upload_to='')),
            ],
        ),
    ]
